import { createFileRoute } from "@tanstack/react-router";
import { absUrl } from "@/lib/seo/site";
import { serviceJsonLdScripts } from "@/lib/seo/jsonLd";
import { Biohazard, Hospital, Beaker, Building2, Pill, School, Wrench, ShieldAlert, PackageX, FileText } from "lucide-react";
import { ServicePageTemplate, type DetailSection } from "@/components/ServicePageTemplate";
import imgHero from "@/assets/svc-biohazard.jpg";
import imgRel0 from "@/assets/svc-hazardous.jpg";
import imgRel1 from "@/assets/svc-destruction.jpg";
import imgRel2 from "@/assets/svc-shred.jpg";

const PAGE_TITLE = "Biohazardous Waste Disposal in Guyana | CEVONS";
const PAGE_DESC = "Safe handling, transport, and compliant treatment of biohazardous waste from hospitals, clinics, health centres, and laboratories.";
const PAGE_URL = "/services/biohazardous-disposal";

export const Route = createFileRoute("/services/biohazardous-disposal")({
  head: () => ({
    meta: [
      { title: PAGE_TITLE },
      { name: "description", content: PAGE_DESC },
      { property: "og:title", content: PAGE_TITLE },
      { property: "og:description", content: PAGE_DESC },
      { property: "og:type", content: "article" },
      { property: "og:url", content: absUrl(PAGE_URL) },
    ],
    links: [{ rel: "canonical", href: absUrl(PAGE_URL) }],
    scripts: serviceJsonLdScripts({ name: PAGE_TITLE, description: PAGE_DESC, path: PAGE_URL, breadcrumb: "Biohazardous Disposal", category: "Industrial", faqs }),
  }),
  component: Page,
});

const uses = [
  { icon: Hospital, title: "Hospitals & Clinics" },
  { icon: Beaker, title: "Laboratories" },
  { icon: Building2, title: "Health Centres" },
  { icon: Pill, title: "Pharmacies" },
  { icon: School, title: "Research Institutions" },
  { icon: Wrench, title: "Dental & Specialty" },
];

const faqs = [
  { q: "What counts as biohazardous waste?", a: "Materials generated by hospitals, clinics, health centres, and laboratories that may contain infectious agents — clinical waste, sharps, pathological waste, contaminated PPE, and related medical streams. If a stream might be biohazardous, treat it as biohazardous until we confirm otherwise." },
  { q: "Do you supply packaging and containers?", a: "Yes. Approved sharps containers and bio bins are supplied at the volume and cadence your facility generates, so waste is contained at the point it's produced." },
  { q: "How often can clinics schedule collection?", a: "As often as needed. High-volume facilities run scheduled weekly collections; smaller clinics run on longer cycles or call-in. We set the cadence to your generation rate." },
  { q: "How is the waste actually treated?", a: "Biohazardous streams follow a controlled destruction and disposal chain — sealed transport, treatment, and final disposal at approved locations. The full route is documented so the outcome is verifiable, not assumed." },
  { q: "What documentation do you provide for health authorities?", a: "Waste tracking and disposal records are provided for every collection, so your facility's compliance file matches the physical work — ready for inspection at any time." },
];

const related = [
  { title: "Hazardous Waste", body: "Regulated hazardous waste handling and disposal.", img: imgRel0, to: "/services/hazardous-waste", icon: ShieldAlert },
  { title: "Product Destruction", body: "Certified product destruction with documentation.", img: imgRel1, to: "/services/product-destruction", icon: PackageX },
  { title: "Document Shredding", body: "Secure document destruction with chain-of-custody.", img: imgRel2, to: "/services/document-shredding", icon: FileText },
];

const detailSections: DetailSection[] = [
  {
    variant: "split-right",
    eyebrow: "Who generates it — and why it can't wait",
    heading: "Biohazardous waste demands a specialist chain from the moment it's produced",
    paragraphs: [
      "Biohazardous waste is generated wherever medicine is practised or biology is studied — hospitals, clinics, health centres, and laboratories, plus pharmacies, dental practices, and research institutions. Every one of those facilities produces material that, handled casually, poses real environmental and sanitary risks.",
      "Medical waste has to be properly handled and disposed of, full stop. The alternative isn't inconvenient — it's dangerous. That's why CEVONS runs a dedicated biohazardous programme separate from general waste and separate from other hazardous streams.",
    ],
    images: [
      { src: "/services/detail/biohazard-disposal-1.webp", alt: "CEVONS collection of biohazardous waste at a healthcare facility" },
    ],
  },
  {
    variant: "split-left",
    eyebrow: "Safe disposal and treatment",
    heading: "A controlled chain from bin to final destruction",
    paragraphs: [
      "CEVONS offers safe disposal and treatment across the full biohazardous chain: supplied containers at the point of generation, sealed transport to the treatment facility, controlled destruction, and documented final disposal.",
      "Each step is logged. That's what \"compliant\" actually means for a healthcare operator — not just that the waste left the building, but that it can be traced from the bin it went into to the site it ended at.",
    ],
    images: [
      { src: "/services/detail/biohazard-disposal-2.webp", alt: "CEVONS biohazardous waste transport and treatment operations" },
    ],
  },
  {
    variant: "band",
    bandEmphasis: true,
    eyebrow: "Public health first",
    heading: "Protecting patients, staff, and the wider environment",
    paragraphs: [
      "The whole point of a biohazardous programme is to prevent environmental and sanitary pollution and to remove risk to public health. Everything else — the containers, the schedules, the paperwork — exists to make that outcome reliable.",
    ],
  },
];

function Page() {
  return (
    <ServicePageTemplate
      eyebrowIcon={Biohazard}
      eyebrowLabel="Industrial"
      breadcrumb="Biohazardous Disposal"
      h1="Biohazardous Waste Disposal"
      subhead="Safe handling, sealed transport, and compliant treatment of biohazardous waste from hospitals, clinics, health centres, and laboratories."
      heroImage={imgHero}
      heroSlot="svc_biohazardous_disposal_hero"
      heroAlt="CEVONS team collecting labelled biohazard containers at a healthcare facility"
      benefits={["Approved containers and labelling","Sealed, compliant transport","Controlled treatment and disposal","Documented chain-of-custody","Scheduled or on-call collection"]}
      commonUses={uses}
      faqs={faqs}
      related={related}
      ctaVariant="specialist"
      serviceSlug="biohazardous-disposal"
      detailSections={detailSections}
      showAssistBand
    />
  );
}
