import { createFileRoute } from "@tanstack/react-router";
import { Biohazard, Hospital, Beaker, Building2, Pill, School, Wrench, ShieldAlert, PackageX, FileText } from "lucide-react";
import { ServicePageTemplate } from "@/components/ServicePageTemplate";
import imgHero from "@/assets/svc-biohazard.jpg";
import imgRel0 from "@/assets/svc-hazardous.jpg";
import imgRel1 from "@/assets/svc-destruction.jpg";
import imgRel2 from "@/assets/svc-shred.jpg";

const PAGE_TITLE = "Biohazardous Waste Disposal in Guyana | CEVON'S";
const PAGE_DESC = "Safe biohazardous waste collection, transport, and compliant disposal for healthcare and laboratory clients in Guyana.";
const PAGE_URL = "/services/biohazardous-disposal";

export const Route = createFileRoute("/services/biohazardous-disposal")({
  head: () => ({
    meta: [
      { title: PAGE_TITLE },
      { name: "description", content: PAGE_DESC },
      { property: "og:title", content: PAGE_TITLE },
      { property: "og:description", content: PAGE_DESC },
      { property: "og:type", content: "article" },
      { property: "og:url", content: PAGE_URL },
    ],
    links: [{ rel: "canonical", href: PAGE_URL }],
  }),
  component: Page,
});

const uses = [
  { icon: Hospital, title: "Hospitals & Clinics" },
  { icon: Beaker, title: "Laboratories" },
  { icon: Building2, title: "Healthcare Facilities" },
  { icon: Pill, title: "Pharmacies" },
  { icon: School, title: "Research Institutions" },
  { icon: Wrench, title: "Dental & Specialty" },
];

const faqs = [
  { q: "What is biohazardous waste?", a: "Materials potentially containing infectious agents — clinical waste, sharps, pathological waste, and related streams generated by healthcare and laboratories." },
  { q: "Do you supply containers?", a: "Yes. Approved sharps containers and bio bins can be supplied based on your generation rate." },
  { q: "Can collection be scheduled?", a: "Yes. Recurring scheduled pickups are common for clinics, labs, and hospitals." },
  { q: "Is documentation provided?", a: "Yes. Waste tracking and disposal documentation can be provided for compliance recordkeeping." },
  { q: "How do I set up service?", a: "Submit a specialist review request with your facility type and estimated waste volumes." },
];

const related = [
  { title: "Hazardous Waste", body: "Regulated hazardous waste handling and disposal.", img: imgRel0, to: "/services/hazardous-waste", icon: ShieldAlert },
  { title: "Product Destruction", body: "Certified product destruction with documentation.", img: imgRel1, to: "/services/product-destruction", icon: PackageX },
  { title: "Document Shredding", body: "Secure document destruction with chain-of-custody.", img: imgRel2, to: "/services/document-shredding", icon: FileText },
];

function Page() {
  return (
    <ServicePageTemplate
      eyebrowIcon={Biohazard}
      eyebrowLabel="Industrial"
      breadcrumb="Biohazardous Disposal"
      h1="Biohazardous Waste Disposal"
      subhead="Safe collection, secure transport, and compliant disposal of biohazardous and clinical waste for healthcare and laboratory clients."
      heroImage={imgHero}
      heroAlt="CEVON'S team collecting labeled biohazard containers at a healthcare facility"
      benefits={["Approved containers and labeling","Trained, equipped crews","Sealed, compliant transport","Documented disposal","Specialist project review"]}
      commonUses={uses}
      faqs={faqs}
      related={related}
      ctaVariant="specialist"
    />
  );
}
