/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRequestRouteImport } from './routes/track-request'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as RequestServiceIndexRouteImport } from './routes/request-service.index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesWastewaterRouteImport } from './routes/services.wastewater'
import { Route as ServicesUsedWasteOilRouteImport } from './routes/services.used-waste-oil'
import { Route as ServicesUsedCookingOilRouteImport } from './routes/services.used-cooking-oil'
import { Route as ServicesTankCleaningRouteImport } from './routes/services.tank-cleaning'
import { Route as ServicesSkipBinDumpsterRentalRouteImport } from './routes/services.skip-bin-dumpster-rental'
import { Route as ServicesSepticServicesRouteImport } from './routes/services.septic-services'
import { Route as ServicesScrapMetalRecyclingRouteImport } from './routes/services.scrap-metal-recycling'
import { Route as ServicesRoadSweepingRouteImport } from './routes/services.road-sweeping'
import { Route as ServicesProductDestructionRouteImport } from './routes/services.product-destruction'
import { Route as ServicesPortableToiletRouteImport } from './routes/services.portable-toilet'
import { Route as ServicesPlasticRecyclingRouteImport } from './routes/services.plastic-recycling'
import { Route as ServicesMaterialRecoveryFacilityRouteImport } from './routes/services.material-recovery-facility'
import { Route as ServicesLandfillOperationsRouteImport } from './routes/services.landfill-operations'
import { Route as ServicesHazardousWasteRouteImport } from './routes/services.hazardous-waste'
import { Route as ServicesGreaseTrapSepticTankRouteImport } from './routes/services.grease-trap-septic-tank'
import { Route as ServicesGeneralWasteManagementRouteImport } from './routes/services.general-waste-management'
import { Route as ServicesGeneralTrashCollectionRouteImport } from './routes/services.general-trash-collection'
import { Route as ServicesDumpsterRentalRouteImport } from './routes/services.dumpster-rental'
import { Route as ServicesDocumentShreddingRouteImport } from './routes/services.document-shredding'
import { Route as ServicesContaminatedSoilRouteImport } from './routes/services.contaminated-soil'
import { Route as ServicesCompactorRentalRouteImport } from './routes/services.compactor-rental'
import { Route as ServicesBiohazardousDisposalRouteImport } from './routes/services.biohazardous-disposal'
import { Route as RequestServiceConfirmationRouteImport } from './routes/request-service.confirmation'
import { Route as DevServiceActionButtonRouteImport } from './routes/dev.service-action-button'
import { Route as DevMotionDebugRouteImport } from './routes/dev.motion-debug'
import { Route as CrmSplatRouteImport } from './routes/crm.$'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNewsroomRouteImport } from './routes/admin.newsroom'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminLeadsIdRouteImport } from './routes/admin.leads.$id'

const TrackRequestRoute = TrackRequestRouteImport.update({
  id: '/track-request',
  path: '/track-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const RequestServiceIndexRoute = RequestServiceIndexRouteImport.update({
  id: '/request-service/',
  path: '/request-service/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesWastewaterRoute = ServicesWastewaterRouteImport.update({
  id: '/wastewater',
  path: '/wastewater',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUsedWasteOilRoute = ServicesUsedWasteOilRouteImport.update({
  id: '/used-waste-oil',
  path: '/used-waste-oil',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUsedCookingOilRoute = ServicesUsedCookingOilRouteImport.update({
  id: '/used-cooking-oil',
  path: '/used-cooking-oil',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTankCleaningRoute = ServicesTankCleaningRouteImport.update({
  id: '/tank-cleaning',
  path: '/tank-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSkipBinDumpsterRentalRoute =
  ServicesSkipBinDumpsterRentalRouteImport.update({
    id: '/skip-bin-dumpster-rental',
    path: '/skip-bin-dumpster-rental',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSepticServicesRoute = ServicesSepticServicesRouteImport.update({
  id: '/septic-services',
  path: '/septic-services',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesScrapMetalRecyclingRoute =
  ServicesScrapMetalRecyclingRouteImport.update({
    id: '/scrap-metal-recycling',
    path: '/scrap-metal-recycling',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesRoadSweepingRoute = ServicesRoadSweepingRouteImport.update({
  id: '/road-sweeping',
  path: '/road-sweeping',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProductDestructionRoute =
  ServicesProductDestructionRouteImport.update({
    id: '/product-destruction',
    path: '/product-destruction',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPortableToiletRoute = ServicesPortableToiletRouteImport.update({
  id: '/portable-toilet',
  path: '/portable-toilet',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPlasticRecyclingRoute =
  ServicesPlasticRecyclingRouteImport.update({
    id: '/plastic-recycling',
    path: '/plastic-recycling',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMaterialRecoveryFacilityRoute =
  ServicesMaterialRecoveryFacilityRouteImport.update({
    id: '/material-recovery-facility',
    path: '/material-recovery-facility',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLandfillOperationsRoute =
  ServicesLandfillOperationsRouteImport.update({
    id: '/landfill-operations',
    path: '/landfill-operations',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHazardousWasteRoute = ServicesHazardousWasteRouteImport.update({
  id: '/hazardous-waste',
  path: '/hazardous-waste',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGreaseTrapSepticTankRoute =
  ServicesGreaseTrapSepticTankRouteImport.update({
    id: '/grease-trap-septic-tank',
    path: '/grease-trap-septic-tank',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGeneralWasteManagementRoute =
  ServicesGeneralWasteManagementRouteImport.update({
    id: '/general-waste-management',
    path: '/general-waste-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGeneralTrashCollectionRoute =
  ServicesGeneralTrashCollectionRouteImport.update({
    id: '/general-trash-collection',
    path: '/general-trash-collection',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDumpsterRentalRoute = ServicesDumpsterRentalRouteImport.update({
  id: '/dumpster-rental',
  path: '/dumpster-rental',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDocumentShreddingRoute =
  ServicesDocumentShreddingRouteImport.update({
    id: '/document-shredding',
    path: '/document-shredding',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesContaminatedSoilRoute =
  ServicesContaminatedSoilRouteImport.update({
    id: '/contaminated-soil',
    path: '/contaminated-soil',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCompactorRentalRoute = ServicesCompactorRentalRouteImport.update({
  id: '/compactor-rental',
  path: '/compactor-rental',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBiohazardousDisposalRoute =
  ServicesBiohazardousDisposalRouteImport.update({
    id: '/biohazardous-disposal',
    path: '/biohazardous-disposal',
    getParentRoute: () => ServicesRoute,
  } as any)
const RequestServiceConfirmationRoute =
  RequestServiceConfirmationRouteImport.update({
    id: '/request-service/confirmation',
    path: '/request-service/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevServiceActionButtonRoute = DevServiceActionButtonRouteImport.update({
  id: '/dev/service-action-button',
  path: '/dev/service-action-button',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMotionDebugRoute = DevMotionDebugRouteImport.update({
  id: '/dev/motion-debug',
  path: '/dev/motion-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSplatRoute = CrmSplatRouteImport.update({
  id: '/crm/$',
  path: '/crm/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsroomRoute = AdminNewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/crm/$': typeof CrmSplatRoute
  '/dev/motion-debug': typeof DevMotionDebugRoute
  '/dev/service-action-button': typeof DevServiceActionButtonRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/biohazardous-disposal': typeof ServicesBiohazardousDisposalRoute
  '/services/compactor-rental': typeof ServicesCompactorRentalRoute
  '/services/contaminated-soil': typeof ServicesContaminatedSoilRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/general-trash-collection': typeof ServicesGeneralTrashCollectionRoute
  '/services/general-waste-management': typeof ServicesGeneralWasteManagementRoute
  '/services/grease-trap-septic-tank': typeof ServicesGreaseTrapSepticTankRoute
  '/services/hazardous-waste': typeof ServicesHazardousWasteRoute
  '/services/landfill-operations': typeof ServicesLandfillOperationsRoute
  '/services/material-recovery-facility': typeof ServicesMaterialRecoveryFacilityRoute
  '/services/plastic-recycling': typeof ServicesPlasticRecyclingRoute
  '/services/portable-toilet': typeof ServicesPortableToiletRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/road-sweeping': typeof ServicesRoadSweepingRoute
  '/services/scrap-metal-recycling': typeof ServicesScrapMetalRecyclingRoute
  '/services/septic-services': typeof ServicesSepticServicesRoute
  '/services/skip-bin-dumpster-rental': typeof ServicesSkipBinDumpsterRentalRoute
  '/services/tank-cleaning': typeof ServicesTankCleaningRoute
  '/services/used-cooking-oil': typeof ServicesUsedCookingOilRoute
  '/services/used-waste-oil': typeof ServicesUsedWasteOilRoute
  '/services/wastewater': typeof ServicesWastewaterRoute
  '/admin/': typeof AdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/request-service/': typeof RequestServiceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/crm/$': typeof CrmSplatRoute
  '/dev/motion-debug': typeof DevMotionDebugRoute
  '/dev/service-action-button': typeof DevServiceActionButtonRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/biohazardous-disposal': typeof ServicesBiohazardousDisposalRoute
  '/services/compactor-rental': typeof ServicesCompactorRentalRoute
  '/services/contaminated-soil': typeof ServicesContaminatedSoilRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/general-trash-collection': typeof ServicesGeneralTrashCollectionRoute
  '/services/general-waste-management': typeof ServicesGeneralWasteManagementRoute
  '/services/grease-trap-septic-tank': typeof ServicesGreaseTrapSepticTankRoute
  '/services/hazardous-waste': typeof ServicesHazardousWasteRoute
  '/services/landfill-operations': typeof ServicesLandfillOperationsRoute
  '/services/material-recovery-facility': typeof ServicesMaterialRecoveryFacilityRoute
  '/services/plastic-recycling': typeof ServicesPlasticRecyclingRoute
  '/services/portable-toilet': typeof ServicesPortableToiletRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/road-sweeping': typeof ServicesRoadSweepingRoute
  '/services/scrap-metal-recycling': typeof ServicesScrapMetalRecyclingRoute
  '/services/septic-services': typeof ServicesSepticServicesRoute
  '/services/skip-bin-dumpster-rental': typeof ServicesSkipBinDumpsterRentalRoute
  '/services/tank-cleaning': typeof ServicesTankCleaningRoute
  '/services/used-cooking-oil': typeof ServicesUsedCookingOilRoute
  '/services/used-waste-oil': typeof ServicesUsedWasteOilRoute
  '/services/wastewater': typeof ServicesWastewaterRoute
  '/admin': typeof AdminIndexRoute
  '/crm': typeof CrmIndexRoute
  '/request-service': typeof RequestServiceIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/crm/$': typeof CrmSplatRoute
  '/dev/motion-debug': typeof DevMotionDebugRoute
  '/dev/service-action-button': typeof DevServiceActionButtonRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/biohazardous-disposal': typeof ServicesBiohazardousDisposalRoute
  '/services/compactor-rental': typeof ServicesCompactorRentalRoute
  '/services/contaminated-soil': typeof ServicesContaminatedSoilRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/general-trash-collection': typeof ServicesGeneralTrashCollectionRoute
  '/services/general-waste-management': typeof ServicesGeneralWasteManagementRoute
  '/services/grease-trap-septic-tank': typeof ServicesGreaseTrapSepticTankRoute
  '/services/hazardous-waste': typeof ServicesHazardousWasteRoute
  '/services/landfill-operations': typeof ServicesLandfillOperationsRoute
  '/services/material-recovery-facility': typeof ServicesMaterialRecoveryFacilityRoute
  '/services/plastic-recycling': typeof ServicesPlasticRecyclingRoute
  '/services/portable-toilet': typeof ServicesPortableToiletRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/road-sweeping': typeof ServicesRoadSweepingRoute
  '/services/scrap-metal-recycling': typeof ServicesScrapMetalRecyclingRoute
  '/services/septic-services': typeof ServicesSepticServicesRoute
  '/services/skip-bin-dumpster-rental': typeof ServicesSkipBinDumpsterRentalRoute
  '/services/tank-cleaning': typeof ServicesTankCleaningRoute
  '/services/used-cooking-oil': typeof ServicesUsedCookingOilRoute
  '/services/used-waste-oil': typeof ServicesUsedWasteOilRoute
  '/services/wastewater': typeof ServicesWastewaterRoute
  '/admin/': typeof AdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/request-service/': typeof RequestServiceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/locations'
    | '/resources'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/track-request'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/newsroom'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/login'
    | '/admin/reset-password'
    | '/crm/$'
    | '/dev/motion-debug'
    | '/dev/service-action-button'
    | '/request-service/confirmation'
    | '/services/biohazardous-disposal'
    | '/services/compactor-rental'
    | '/services/contaminated-soil'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/general-trash-collection'
    | '/services/general-waste-management'
    | '/services/grease-trap-septic-tank'
    | '/services/hazardous-waste'
    | '/services/landfill-operations'
    | '/services/material-recovery-facility'
    | '/services/plastic-recycling'
    | '/services/portable-toilet'
    | '/services/product-destruction'
    | '/services/road-sweeping'
    | '/services/scrap-metal-recycling'
    | '/services/septic-services'
    | '/services/skip-bin-dumpster-rental'
    | '/services/tank-cleaning'
    | '/services/used-cooking-oil'
    | '/services/used-waste-oil'
    | '/services/wastewater'
    | '/admin/'
    | '/crm/'
    | '/request-service/'
    | '/services/'
    | '/admin/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/locations'
    | '/resources'
    | '/sitemap'
    | '/sitemap.xml'
    | '/track-request'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/newsroom'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/login'
    | '/admin/reset-password'
    | '/crm/$'
    | '/dev/motion-debug'
    | '/dev/service-action-button'
    | '/request-service/confirmation'
    | '/services/biohazardous-disposal'
    | '/services/compactor-rental'
    | '/services/contaminated-soil'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/general-trash-collection'
    | '/services/general-waste-management'
    | '/services/grease-trap-septic-tank'
    | '/services/hazardous-waste'
    | '/services/landfill-operations'
    | '/services/material-recovery-facility'
    | '/services/plastic-recycling'
    | '/services/portable-toilet'
    | '/services/product-destruction'
    | '/services/road-sweeping'
    | '/services/scrap-metal-recycling'
    | '/services/septic-services'
    | '/services/skip-bin-dumpster-rental'
    | '/services/tank-cleaning'
    | '/services/used-cooking-oil'
    | '/services/used-waste-oil'
    | '/services/wastewater'
    | '/admin'
    | '/crm'
    | '/request-service'
    | '/services'
    | '/admin/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/locations'
    | '/resources'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/track-request'
    | '/admin/audit'
    | '/admin/conversations'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/newsroom'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin_/login'
    | '/admin_/reset-password'
    | '/crm/$'
    | '/dev/motion-debug'
    | '/dev/service-action-button'
    | '/request-service/confirmation'
    | '/services/biohazardous-disposal'
    | '/services/compactor-rental'
    | '/services/contaminated-soil'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/general-trash-collection'
    | '/services/general-waste-management'
    | '/services/grease-trap-septic-tank'
    | '/services/hazardous-waste'
    | '/services/landfill-operations'
    | '/services/material-recovery-facility'
    | '/services/plastic-recycling'
    | '/services/portable-toilet'
    | '/services/product-destruction'
    | '/services/road-sweeping'
    | '/services/scrap-metal-recycling'
    | '/services/septic-services'
    | '/services/skip-bin-dumpster-rental'
    | '/services/tank-cleaning'
    | '/services/used-cooking-oil'
    | '/services/used-waste-oil'
    | '/services/wastewater'
    | '/admin/'
    | '/crm/'
    | '/request-service/'
    | '/services/'
    | '/admin/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LocationsRoute: typeof LocationsRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRequestRoute: typeof TrackRequestRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  CrmSplatRoute: typeof CrmSplatRoute
  DevMotionDebugRoute: typeof DevMotionDebugRoute
  DevServiceActionButtonRoute: typeof DevServiceActionButtonRoute
  RequestServiceConfirmationRoute: typeof RequestServiceConfirmationRoute
  CrmIndexRoute: typeof CrmIndexRoute
  RequestServiceIndexRoute: typeof RequestServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-request': {
      id: '/track-request'
      path: '/track-request'
      fullPath: '/track-request'
      preLoaderRoute: typeof TrackRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/request-service/': {
      id: '/request-service/'
      path: '/request-service'
      fullPath: '/request-service/'
      preLoaderRoute: typeof RequestServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/wastewater': {
      id: '/services/wastewater'
      path: '/wastewater'
      fullPath: '/services/wastewater'
      preLoaderRoute: typeof ServicesWastewaterRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/used-waste-oil': {
      id: '/services/used-waste-oil'
      path: '/used-waste-oil'
      fullPath: '/services/used-waste-oil'
      preLoaderRoute: typeof ServicesUsedWasteOilRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/used-cooking-oil': {
      id: '/services/used-cooking-oil'
      path: '/used-cooking-oil'
      fullPath: '/services/used-cooking-oil'
      preLoaderRoute: typeof ServicesUsedCookingOilRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tank-cleaning': {
      id: '/services/tank-cleaning'
      path: '/tank-cleaning'
      fullPath: '/services/tank-cleaning'
      preLoaderRoute: typeof ServicesTankCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/skip-bin-dumpster-rental': {
      id: '/services/skip-bin-dumpster-rental'
      path: '/skip-bin-dumpster-rental'
      fullPath: '/services/skip-bin-dumpster-rental'
      preLoaderRoute: typeof ServicesSkipBinDumpsterRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/septic-services': {
      id: '/services/septic-services'
      path: '/septic-services'
      fullPath: '/services/septic-services'
      preLoaderRoute: typeof ServicesSepticServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/scrap-metal-recycling': {
      id: '/services/scrap-metal-recycling'
      path: '/scrap-metal-recycling'
      fullPath: '/services/scrap-metal-recycling'
      preLoaderRoute: typeof ServicesScrapMetalRecyclingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/road-sweeping': {
      id: '/services/road-sweeping'
      path: '/road-sweeping'
      fullPath: '/services/road-sweeping'
      preLoaderRoute: typeof ServicesRoadSweepingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/product-destruction': {
      id: '/services/product-destruction'
      path: '/product-destruction'
      fullPath: '/services/product-destruction'
      preLoaderRoute: typeof ServicesProductDestructionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/portable-toilet': {
      id: '/services/portable-toilet'
      path: '/portable-toilet'
      fullPath: '/services/portable-toilet'
      preLoaderRoute: typeof ServicesPortableToiletRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/plastic-recycling': {
      id: '/services/plastic-recycling'
      path: '/plastic-recycling'
      fullPath: '/services/plastic-recycling'
      preLoaderRoute: typeof ServicesPlasticRecyclingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/material-recovery-facility': {
      id: '/services/material-recovery-facility'
      path: '/material-recovery-facility'
      fullPath: '/services/material-recovery-facility'
      preLoaderRoute: typeof ServicesMaterialRecoveryFacilityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landfill-operations': {
      id: '/services/landfill-operations'
      path: '/landfill-operations'
      fullPath: '/services/landfill-operations'
      preLoaderRoute: typeof ServicesLandfillOperationsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hazardous-waste': {
      id: '/services/hazardous-waste'
      path: '/hazardous-waste'
      fullPath: '/services/hazardous-waste'
      preLoaderRoute: typeof ServicesHazardousWasteRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/grease-trap-septic-tank': {
      id: '/services/grease-trap-septic-tank'
      path: '/grease-trap-septic-tank'
      fullPath: '/services/grease-trap-septic-tank'
      preLoaderRoute: typeof ServicesGreaseTrapSepticTankRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/general-waste-management': {
      id: '/services/general-waste-management'
      path: '/general-waste-management'
      fullPath: '/services/general-waste-management'
      preLoaderRoute: typeof ServicesGeneralWasteManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/general-trash-collection': {
      id: '/services/general-trash-collection'
      path: '/general-trash-collection'
      fullPath: '/services/general-trash-collection'
      preLoaderRoute: typeof ServicesGeneralTrashCollectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dumpster-rental': {
      id: '/services/dumpster-rental'
      path: '/dumpster-rental'
      fullPath: '/services/dumpster-rental'
      preLoaderRoute: typeof ServicesDumpsterRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/document-shredding': {
      id: '/services/document-shredding'
      path: '/document-shredding'
      fullPath: '/services/document-shredding'
      preLoaderRoute: typeof ServicesDocumentShreddingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/contaminated-soil': {
      id: '/services/contaminated-soil'
      path: '/contaminated-soil'
      fullPath: '/services/contaminated-soil'
      preLoaderRoute: typeof ServicesContaminatedSoilRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/compactor-rental': {
      id: '/services/compactor-rental'
      path: '/compactor-rental'
      fullPath: '/services/compactor-rental'
      preLoaderRoute: typeof ServicesCompactorRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/biohazardous-disposal': {
      id: '/services/biohazardous-disposal'
      path: '/biohazardous-disposal'
      fullPath: '/services/biohazardous-disposal'
      preLoaderRoute: typeof ServicesBiohazardousDisposalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/request-service/confirmation': {
      id: '/request-service/confirmation'
      path: '/request-service/confirmation'
      fullPath: '/request-service/confirmation'
      preLoaderRoute: typeof RequestServiceConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/service-action-button': {
      id: '/dev/service-action-button'
      path: '/dev/service-action-button'
      fullPath: '/dev/service-action-button'
      preLoaderRoute: typeof DevServiceActionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/motion-debug': {
      id: '/dev/motion-debug'
      path: '/dev/motion-debug'
      fullPath: '/dev/motion-debug'
      preLoaderRoute: typeof DevMotionDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$': {
      id: '/crm/$'
      path: '/crm/$'
      fullPath: '/crm/$'
      preLoaderRoute: typeof CrmSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsroom': {
      id: '/admin/newsroom'
      path: '/newsroom'
      fullPath: '/admin/newsroom'
      preLoaderRoute: typeof AdminNewsroomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
  }
}

interface AdminLeadsRouteChildren {
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsIdRoute: AdminLeadsIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsroomRoute: typeof AdminNewsroomRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsroomRoute: AdminNewsroomRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesBiohazardousDisposalRoute: typeof ServicesBiohazardousDisposalRoute
  ServicesCompactorRentalRoute: typeof ServicesCompactorRentalRoute
  ServicesContaminatedSoilRoute: typeof ServicesContaminatedSoilRoute
  ServicesDocumentShreddingRoute: typeof ServicesDocumentShreddingRoute
  ServicesDumpsterRentalRoute: typeof ServicesDumpsterRentalRoute
  ServicesGeneralTrashCollectionRoute: typeof ServicesGeneralTrashCollectionRoute
  ServicesGeneralWasteManagementRoute: typeof ServicesGeneralWasteManagementRoute
  ServicesGreaseTrapSepticTankRoute: typeof ServicesGreaseTrapSepticTankRoute
  ServicesHazardousWasteRoute: typeof ServicesHazardousWasteRoute
  ServicesLandfillOperationsRoute: typeof ServicesLandfillOperationsRoute
  ServicesMaterialRecoveryFacilityRoute: typeof ServicesMaterialRecoveryFacilityRoute
  ServicesPlasticRecyclingRoute: typeof ServicesPlasticRecyclingRoute
  ServicesPortableToiletRoute: typeof ServicesPortableToiletRoute
  ServicesProductDestructionRoute: typeof ServicesProductDestructionRoute
  ServicesRoadSweepingRoute: typeof ServicesRoadSweepingRoute
  ServicesScrapMetalRecyclingRoute: typeof ServicesScrapMetalRecyclingRoute
  ServicesSepticServicesRoute: typeof ServicesSepticServicesRoute
  ServicesSkipBinDumpsterRentalRoute: typeof ServicesSkipBinDumpsterRentalRoute
  ServicesTankCleaningRoute: typeof ServicesTankCleaningRoute
  ServicesUsedCookingOilRoute: typeof ServicesUsedCookingOilRoute
  ServicesUsedWasteOilRoute: typeof ServicesUsedWasteOilRoute
  ServicesWastewaterRoute: typeof ServicesWastewaterRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBiohazardousDisposalRoute: ServicesBiohazardousDisposalRoute,
  ServicesCompactorRentalRoute: ServicesCompactorRentalRoute,
  ServicesContaminatedSoilRoute: ServicesContaminatedSoilRoute,
  ServicesDocumentShreddingRoute: ServicesDocumentShreddingRoute,
  ServicesDumpsterRentalRoute: ServicesDumpsterRentalRoute,
  ServicesGeneralTrashCollectionRoute: ServicesGeneralTrashCollectionRoute,
  ServicesGeneralWasteManagementRoute: ServicesGeneralWasteManagementRoute,
  ServicesGreaseTrapSepticTankRoute: ServicesGreaseTrapSepticTankRoute,
  ServicesHazardousWasteRoute: ServicesHazardousWasteRoute,
  ServicesLandfillOperationsRoute: ServicesLandfillOperationsRoute,
  ServicesMaterialRecoveryFacilityRoute: ServicesMaterialRecoveryFacilityRoute,
  ServicesPlasticRecyclingRoute: ServicesPlasticRecyclingRoute,
  ServicesPortableToiletRoute: ServicesPortableToiletRoute,
  ServicesProductDestructionRoute: ServicesProductDestructionRoute,
  ServicesRoadSweepingRoute: ServicesRoadSweepingRoute,
  ServicesScrapMetalRecyclingRoute: ServicesScrapMetalRecyclingRoute,
  ServicesSepticServicesRoute: ServicesSepticServicesRoute,
  ServicesSkipBinDumpsterRentalRoute: ServicesSkipBinDumpsterRentalRoute,
  ServicesTankCleaningRoute: ServicesTankCleaningRoute,
  ServicesUsedCookingOilRoute: ServicesUsedCookingOilRoute,
  ServicesUsedWasteOilRoute: ServicesUsedWasteOilRoute,
  ServicesWastewaterRoute: ServicesWastewaterRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LocationsRoute: LocationsRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRequestRoute: TrackRequestRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  CrmSplatRoute: CrmSplatRoute,
  DevMotionDebugRoute: DevMotionDebugRoute,
  DevServiceActionButtonRoute: DevServiceActionButtonRoute,
  RequestServiceConfirmationRoute: RequestServiceConfirmationRoute,
  CrmIndexRoute: CrmIndexRoute,
  RequestServiceIndexRoute: RequestServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
