/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRequestRouteImport } from './routes/track-request'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RequestServiceRouteImport } from './routes/request-service'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWastewaterTreatmentRouteImport } from './routes/services.wastewater-treatment'
import { Route as ServicesWasteOilRecyclingRouteImport } from './routes/services.waste-oil-recycling'
import { Route as ServicesSkipBinRentalRouteImport } from './routes/services.skip-bin-rental'
import { Route as ServicesSepticTankClearanceRouteImport } from './routes/services.septic-tank-clearance'
import { Route as ServicesScrapMetalCollectionRouteImport } from './routes/services.scrap-metal-collection'
import { Route as ServicesResidentialGarbageCollectionRouteImport } from './routes/services.residential-garbage-collection'
import { Route as ServicesProductDestructionRouteImport } from './routes/services.product-destruction'
import { Route as ServicesPortableToiletRentalRouteImport } from './routes/services.portable-toilet-rental'
import { Route as ServicesDumpsterRentalRouteImport } from './routes/services.dumpster-rental'
import { Route as ServicesDocumentShreddingRouteImport } from './routes/services.document-shredding'
import { Route as ServicesCommercialGarbageCollectionRouteImport } from './routes/services.commercial-garbage-collection'
import { Route as RequestServiceConfirmationRouteImport } from './routes/request-service.confirmation'

const TrackRequestRoute = TrackRequestRouteImport.update({
  id: '/track-request',
  path: '/track-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestServiceRoute = RequestServiceRouteImport.update({
  id: '/request-service',
  path: '/request-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWastewaterTreatmentRoute =
  ServicesWastewaterTreatmentRouteImport.update({
    id: '/wastewater-treatment',
    path: '/wastewater-treatment',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWasteOilRecyclingRoute =
  ServicesWasteOilRecyclingRouteImport.update({
    id: '/waste-oil-recycling',
    path: '/waste-oil-recycling',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSkipBinRentalRoute = ServicesSkipBinRentalRouteImport.update({
  id: '/skip-bin-rental',
  path: '/skip-bin-rental',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSepticTankClearanceRoute =
  ServicesSepticTankClearanceRouteImport.update({
    id: '/septic-tank-clearance',
    path: '/septic-tank-clearance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesScrapMetalCollectionRoute =
  ServicesScrapMetalCollectionRouteImport.update({
    id: '/scrap-metal-collection',
    path: '/scrap-metal-collection',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesResidentialGarbageCollectionRoute =
  ServicesResidentialGarbageCollectionRouteImport.update({
    id: '/residential-garbage-collection',
    path: '/residential-garbage-collection',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesProductDestructionRoute =
  ServicesProductDestructionRouteImport.update({
    id: '/product-destruction',
    path: '/product-destruction',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPortableToiletRentalRoute =
  ServicesPortableToiletRentalRouteImport.update({
    id: '/portable-toilet-rental',
    path: '/portable-toilet-rental',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDumpsterRentalRoute = ServicesDumpsterRentalRouteImport.update({
  id: '/dumpster-rental',
  path: '/dumpster-rental',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDocumentShreddingRoute =
  ServicesDocumentShreddingRouteImport.update({
    id: '/document-shredding',
    path: '/document-shredding',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCommercialGarbageCollectionRoute =
  ServicesCommercialGarbageCollectionRouteImport.update({
    id: '/commercial-garbage-collection',
    path: '/commercial-garbage-collection',
    getParentRoute: () => ServicesRoute,
  } as any)
const RequestServiceConfirmationRoute =
  RequestServiceConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => RequestServiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/request-service': typeof RequestServiceRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/track-request': typeof TrackRequestRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/commercial-garbage-collection': typeof ServicesCommercialGarbageCollectionRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/portable-toilet-rental': typeof ServicesPortableToiletRentalRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/residential-garbage-collection': typeof ServicesResidentialGarbageCollectionRoute
  '/services/scrap-metal-collection': typeof ServicesScrapMetalCollectionRoute
  '/services/septic-tank-clearance': typeof ServicesSepticTankClearanceRoute
  '/services/skip-bin-rental': typeof ServicesSkipBinRentalRoute
  '/services/waste-oil-recycling': typeof ServicesWasteOilRecyclingRoute
  '/services/wastewater-treatment': typeof ServicesWastewaterTreatmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/request-service': typeof RequestServiceRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/track-request': typeof TrackRequestRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/commercial-garbage-collection': typeof ServicesCommercialGarbageCollectionRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/portable-toilet-rental': typeof ServicesPortableToiletRentalRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/residential-garbage-collection': typeof ServicesResidentialGarbageCollectionRoute
  '/services/scrap-metal-collection': typeof ServicesScrapMetalCollectionRoute
  '/services/septic-tank-clearance': typeof ServicesSepticTankClearanceRoute
  '/services/skip-bin-rental': typeof ServicesSkipBinRentalRoute
  '/services/waste-oil-recycling': typeof ServicesWasteOilRecyclingRoute
  '/services/wastewater-treatment': typeof ServicesWastewaterTreatmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/industries': typeof IndustriesRoute
  '/locations': typeof LocationsRoute
  '/request-service': typeof RequestServiceRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/track-request': typeof TrackRequestRoute
  '/request-service/confirmation': typeof RequestServiceConfirmationRoute
  '/services/commercial-garbage-collection': typeof ServicesCommercialGarbageCollectionRoute
  '/services/document-shredding': typeof ServicesDocumentShreddingRoute
  '/services/dumpster-rental': typeof ServicesDumpsterRentalRoute
  '/services/portable-toilet-rental': typeof ServicesPortableToiletRentalRoute
  '/services/product-destruction': typeof ServicesProductDestructionRoute
  '/services/residential-garbage-collection': typeof ServicesResidentialGarbageCollectionRoute
  '/services/scrap-metal-collection': typeof ServicesScrapMetalCollectionRoute
  '/services/septic-tank-clearance': typeof ServicesSepticTankClearanceRoute
  '/services/skip-bin-rental': typeof ServicesSkipBinRentalRoute
  '/services/waste-oil-recycling': typeof ServicesWasteOilRecyclingRoute
  '/services/wastewater-treatment': typeof ServicesWastewaterTreatmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/industries'
    | '/locations'
    | '/request-service'
    | '/resources'
    | '/services'
    | '/track-request'
    | '/request-service/confirmation'
    | '/services/commercial-garbage-collection'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/portable-toilet-rental'
    | '/services/product-destruction'
    | '/services/residential-garbage-collection'
    | '/services/scrap-metal-collection'
    | '/services/septic-tank-clearance'
    | '/services/skip-bin-rental'
    | '/services/waste-oil-recycling'
    | '/services/wastewater-treatment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/industries'
    | '/locations'
    | '/request-service'
    | '/resources'
    | '/services'
    | '/track-request'
    | '/request-service/confirmation'
    | '/services/commercial-garbage-collection'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/portable-toilet-rental'
    | '/services/product-destruction'
    | '/services/residential-garbage-collection'
    | '/services/scrap-metal-collection'
    | '/services/septic-tank-clearance'
    | '/services/skip-bin-rental'
    | '/services/waste-oil-recycling'
    | '/services/wastewater-treatment'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/industries'
    | '/locations'
    | '/request-service'
    | '/resources'
    | '/services'
    | '/track-request'
    | '/request-service/confirmation'
    | '/services/commercial-garbage-collection'
    | '/services/document-shredding'
    | '/services/dumpster-rental'
    | '/services/portable-toilet-rental'
    | '/services/product-destruction'
    | '/services/residential-garbage-collection'
    | '/services/scrap-metal-collection'
    | '/services/septic-tank-clearance'
    | '/services/skip-bin-rental'
    | '/services/waste-oil-recycling'
    | '/services/wastewater-treatment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IndustriesRoute: typeof IndustriesRoute
  LocationsRoute: typeof LocationsRoute
  RequestServiceRoute: typeof RequestServiceRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TrackRequestRoute: typeof TrackRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-request': {
      id: '/track-request'
      path: '/track-request'
      fullPath: '/track-request'
      preLoaderRoute: typeof TrackRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-service': {
      id: '/request-service'
      path: '/request-service'
      fullPath: '/request-service'
      preLoaderRoute: typeof RequestServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wastewater-treatment': {
      id: '/services/wastewater-treatment'
      path: '/wastewater-treatment'
      fullPath: '/services/wastewater-treatment'
      preLoaderRoute: typeof ServicesWastewaterTreatmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/waste-oil-recycling': {
      id: '/services/waste-oil-recycling'
      path: '/waste-oil-recycling'
      fullPath: '/services/waste-oil-recycling'
      preLoaderRoute: typeof ServicesWasteOilRecyclingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/skip-bin-rental': {
      id: '/services/skip-bin-rental'
      path: '/skip-bin-rental'
      fullPath: '/services/skip-bin-rental'
      preLoaderRoute: typeof ServicesSkipBinRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/septic-tank-clearance': {
      id: '/services/septic-tank-clearance'
      path: '/septic-tank-clearance'
      fullPath: '/services/septic-tank-clearance'
      preLoaderRoute: typeof ServicesSepticTankClearanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/scrap-metal-collection': {
      id: '/services/scrap-metal-collection'
      path: '/scrap-metal-collection'
      fullPath: '/services/scrap-metal-collection'
      preLoaderRoute: typeof ServicesScrapMetalCollectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential-garbage-collection': {
      id: '/services/residential-garbage-collection'
      path: '/residential-garbage-collection'
      fullPath: '/services/residential-garbage-collection'
      preLoaderRoute: typeof ServicesResidentialGarbageCollectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/product-destruction': {
      id: '/services/product-destruction'
      path: '/product-destruction'
      fullPath: '/services/product-destruction'
      preLoaderRoute: typeof ServicesProductDestructionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/portable-toilet-rental': {
      id: '/services/portable-toilet-rental'
      path: '/portable-toilet-rental'
      fullPath: '/services/portable-toilet-rental'
      preLoaderRoute: typeof ServicesPortableToiletRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dumpster-rental': {
      id: '/services/dumpster-rental'
      path: '/dumpster-rental'
      fullPath: '/services/dumpster-rental'
      preLoaderRoute: typeof ServicesDumpsterRentalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/document-shredding': {
      id: '/services/document-shredding'
      path: '/document-shredding'
      fullPath: '/services/document-shredding'
      preLoaderRoute: typeof ServicesDocumentShreddingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial-garbage-collection': {
      id: '/services/commercial-garbage-collection'
      path: '/commercial-garbage-collection'
      fullPath: '/services/commercial-garbage-collection'
      preLoaderRoute: typeof ServicesCommercialGarbageCollectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/request-service/confirmation': {
      id: '/request-service/confirmation'
      path: '/confirmation'
      fullPath: '/request-service/confirmation'
      preLoaderRoute: typeof RequestServiceConfirmationRouteImport
      parentRoute: typeof RequestServiceRoute
    }
  }
}

interface RequestServiceRouteChildren {
  RequestServiceConfirmationRoute: typeof RequestServiceConfirmationRoute
}

const RequestServiceRouteChildren: RequestServiceRouteChildren = {
  RequestServiceConfirmationRoute: RequestServiceConfirmationRoute,
}

const RequestServiceRouteWithChildren = RequestServiceRoute._addFileChildren(
  RequestServiceRouteChildren,
)

interface ServicesRouteChildren {
  ServicesCommercialGarbageCollectionRoute: typeof ServicesCommercialGarbageCollectionRoute
  ServicesDocumentShreddingRoute: typeof ServicesDocumentShreddingRoute
  ServicesDumpsterRentalRoute: typeof ServicesDumpsterRentalRoute
  ServicesPortableToiletRentalRoute: typeof ServicesPortableToiletRentalRoute
  ServicesProductDestructionRoute: typeof ServicesProductDestructionRoute
  ServicesResidentialGarbageCollectionRoute: typeof ServicesResidentialGarbageCollectionRoute
  ServicesScrapMetalCollectionRoute: typeof ServicesScrapMetalCollectionRoute
  ServicesSepticTankClearanceRoute: typeof ServicesSepticTankClearanceRoute
  ServicesSkipBinRentalRoute: typeof ServicesSkipBinRentalRoute
  ServicesWasteOilRecyclingRoute: typeof ServicesWasteOilRecyclingRoute
  ServicesWastewaterTreatmentRoute: typeof ServicesWastewaterTreatmentRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCommercialGarbageCollectionRoute:
    ServicesCommercialGarbageCollectionRoute,
  ServicesDocumentShreddingRoute: ServicesDocumentShreddingRoute,
  ServicesDumpsterRentalRoute: ServicesDumpsterRentalRoute,
  ServicesPortableToiletRentalRoute: ServicesPortableToiletRentalRoute,
  ServicesProductDestructionRoute: ServicesProductDestructionRoute,
  ServicesResidentialGarbageCollectionRoute:
    ServicesResidentialGarbageCollectionRoute,
  ServicesScrapMetalCollectionRoute: ServicesScrapMetalCollectionRoute,
  ServicesSepticTankClearanceRoute: ServicesSepticTankClearanceRoute,
  ServicesSkipBinRentalRoute: ServicesSkipBinRentalRoute,
  ServicesWasteOilRecyclingRoute: ServicesWasteOilRecyclingRoute,
  ServicesWastewaterTreatmentRoute: ServicesWastewaterTreatmentRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IndustriesRoute: IndustriesRoute,
  LocationsRoute: LocationsRoute,
  RequestServiceRoute: RequestServiceRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TrackRequestRoute: TrackRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
